### ISSUE TITLE
error message while running `cgatshowcase transdiffexprs --help`

### ISSUE THREAD

**Issue by amayer21** [cgat-developers/cgat-showcase#21]
This is the new error message I got when running the command 
```cgatshowcase transdiffexprs --help```:

`
Traceback (most recent call last):
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/bin/cgatshowcase", line 11, in <module>
    load_entry_point('cgatshowcase==0.1.5', 'console_scripts', 'cgatshowcase')()
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/cgatshowcase/entry.py", line 89, in main
    module = imp.load_module(pipeline, file, pathname, description)
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/cgatshowcase/pipeline_transdiffexprs.py", line 117, in <module>
    from cgatcore import pipeline as P
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/cgatcore/pipeline/__init__.py", line 327, in <module>
    from cgatcore.pipeline.control import *
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/cgatcore/pipeline/control.py", line 40, in <module>
    import drmaa
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/drmaa/__init__.py", line 63, in <module>
    from .session import JobInfo, JobTemplate, Session
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/drmaa/session.py", line 39, in <module>
    from drmaa.helpers import (adapt_rusage, Attribute, attribute_names_iterator,
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/drmaa/helpers.py", line 36, in <module>
    from drmaa.wrappers import (drmaa_attr_names_t, drmaa_attr_values_t,
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/drmaa/wrappers.py", line 56, in <module>
    _lib = CDLL(libpath, mode=RTLD_GLOBAL)
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /cm/shared/apps/torque/current/lib/libdrmaa.so.0: undefined symbol: _Z19drmaa_attrib_lookupPKcj
`

Not sure what to do... (could it be due to the problem while installing cgat-core?)

**Comment by amayer21** [comment]
Maybe a tiny bit more readable (?)

```Traceback (most recent call last):
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/bin/cgatshowcase", line 11, in <module>
    load_entry_point('cgatshowcase==0.1.5', 'console_scripts', 'cgatshowcase')()
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/cgatshowcase/entry.py", line 89, in main
    module = imp.load_module(pipeline, file, pathname, description)
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/cgatshowcase/pipeline_transdiffexprs.py", line 117, in <module>
    from cgatcore import pipeline as P
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/cgatcore/pipeline/__init__.py", line 327, in <module>
    from cgatcore.pipeline.control import *
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/cgatcore/pipeline/control.py", line 40, in <module>
    import drmaa
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/drmaa/__init__.py", line 63, in <module>
    from .session import JobInfo, JobTemplate, Session
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/drmaa/session.py", line 39, in <module>
    from drmaa.helpers import (adapt_rusage, Attribute, attribute_names_iterator,
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/drmaa/helpers.py", line 36, in <module>
    from drmaa.wrappers import (drmaa_attr_names_t, drmaa_attr_values_t,
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/drmaa/wrappers.py", line 56, in <module>
    _lib = CDLL(libpath, mode=RTLD_GLOBAL)
  File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /cm/shared/apps/torque/current/lib/libdrmaa.so.0: undefined symbol: _Z19drmaa_attrib_lookupPKcj```

**Comment by Acribbs** [comment]
yeh this is stating that your environment and the entry point to the cgatshowcase isn't correctly configured. 

I think you should start with a clean environment and do the following:

```
conda env create -n cgatshowcase
conda install -c cgat cgatshowcase
conda activate cgatshowcase
```

**Comment by amayer21** [comment]
OK, I'll do that tomorrow. 
Will also reinstall cgatcore with `conda install -c bioconda cgatcore` to be sure it's properly set up.
Thanks for your help!

**Comment by Acribbs** [comment]
Let me know if you get any further errors.
